### ISSUE TITLE
Include or mention "Abandon on startup" metric

### ISSUE THREAD

**Issue by tonihei** [cta-standards/R4WG20-QoE-Metrics#4]
The definition of "Average initial startup time" goes into great detail about the fact that some playbacks may never have been started and shouldn't be included in this average.

What's missing is a reference or mention of the related metric of "Abandoned on startup percentage = Percentage of playbacks were video never reached smooth playback."  
This metric is important to understand the "average initial startup time". For example, if a lot of users are prepared to wait longer for their playback to start, the startup time will go up (which looks bad), but this could be explained by the reduced abandonment rate (which is actually good).

It would also be possible to mention this as part of the histogram approach to startup time where the "not started" case should be part of the histogram.

**Comment by mlevine84** [comment]
Conviva & Mux will provide definition of Exit Before Video Start (EBVS) metric to address the comment.

**Comment by njadia** [comment]
EBVS - Exits Before Video Start (EBVS) measures the Attempts that terminated before the video started, without a reported fatal error. This metric in percentage shows the sum of Attempts that ended before video start without a reported fatal error, within the selected interval. If a fatal error is reported when t he video terminates before starting, the video termination is counted as a Video Start Failure (VSF) instead of EBVS .

**Comment by mlevine84** [comment]
Added a Note to Standardized Aggregate Metrics section of Google doc.
